name: CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - name: Debugging NPM_TOKEN
        run: echo -n "${{ secrets.NPM_TOKEN }}" | tail -c 4
      - name: Semantic Release
        run: "yarn ci:publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
